resources/lang/vendor/cookieConsent/en/texts.php
resources/markdown/policy.md
resources/markdown/terms.md

Policy and terms page content updated(WIP - terms and policy need to be generated).

cookie consent text updated.

---

app/Actions/Project/CreateNewProject.php
app/Actions/Project/UpdateProject.php
app/Http/Controllers/ProjectController.php
app/Models/Project.php
app/Providers/JetstreamServiceProvider.php
database/migrations/2021_11_20_174756_create_projects_table.php
package-lock.json
package.json
resources/js/Jetstream/StudyIndex.vue
resources/js/Jetstream/Welcome.vue
resources/js/Pages/Dashboard.vue
resources/js/Pages/Project/Partials/Delete.vue
resources/js/Pages/Project/Partials/Details.vue
resources/js/Pages/Project/Settings.vue
resources/js/Pages/Project/Show.vue
resources/js/Pages/Teams/Partials/CreateTeamForm.vue
resources/js/Pages/Teams/Partials/TeamMemberManager.vue
resources/js/Shared/ActivityDetails.vue
routes/web.php
tailwind.config.js

- Added marked package for description text area
- Project
- Added Model
- Actions: CreateNewProject, UpdateProject
- Added migration
- Front end views updated ~ Dashboard, Welcome, Project ( Show, Settings, Delete, Details, Activity)
- Routes
Stale commits from the Roles and Permissions
- Create team form
- Team member Manager form updates
- JetStreamServiceProvider team roles ~ project, study also added

Projects implementation

---

.env.example
docker-compose.yml

docker-compose and env.example updated

Pgsql migration

---

composer.json
config/app.php
config/audit.php
database/migrations/2021_11_21_222356_create_audits_table.php

- Added owen-it audit package
- Migration
- Config file added

Model audit trail implementation

---

app/Http/Middleware/VerifyCsrfToken.php
composer.json
composer.lock
config/support-bubble.php
public/css/app.css
resources/lang/vendor/support-bubble/en/support-bubble.php
resources/views/app.blade.php
routes/web.php
tailwind.config.js

Added support bubble

---

app/Models/Announcement.php
app/Models/User.php

Creating the Eloquent Model for the Announcement table and defining the Many to One relationship with the User.
To read more about 
Laravel Model follow the link: https://laravel.com/docs/8.x/eloquent
Eloquent Relationship: https://laravel.com/docs/8.x/eloquent-relationships

Create an announcement model.

---

app/Models/Announcement.php
database/migrations/2021_11_29_151352_announcement.php
database/seeders/AnnouncementSeeder.php
database/seeders/DatabaseSeeder.php

Generating migrations: https://laravel.com/docs/8.x/migrations#generating-migrations
DB Schemas column types: https://laravel.com/docs/8.x/migrations#available-column-types

Create the Announcement migration to persist data to backend DB.

---

resources/js/Pages/Project/Index.vue

Fix Issue #109

---

app/Actions/Jetstream/AddTeamMember.php
app/Actions/Jetstream/CreateTeam.php
app/Actions/Jetstream/DeleteTeam.php
app/Actions/Jetstream/InviteTeamMember.php
app/Actions/Jetstream/RemoveTeamMember.php
app/Actions/Jetstream/UpdateTeamName.php
resources/js/Jetstream/Banner.vue
resources/js/Shared/AnnouncementBanner.vue

1. make the team notification banner consitent
2. Add flash message to Team CRUD actions
Fixes #126 #63

Make notification banner consistent and add flash message to Team's CRUD operation.

---

app/Actions/License/GetLicense.php
app/Http/Controllers/StudyController.php
resources/js/Pages/Study/About.vue

Fixes License issue.

---

app/Actions/Project/CreateNewProject.php
app/Actions/Project/UpdateProject.php
app/Actions/Study/CreateNewStudy.php
app/Actions/Study/UpdateStudy.php
resources/js/Pages/Project/Partials/Create.vue
resources/js/Pages/Project/Partials/Details.vue
resources/js/Pages/Study/Partials/Create.vue
resources/js/Pages/Study/Partials/Details.vue
resources/js/Shared/Submission.vue

Add Validation to License.

---

app/Actions/Project/UpdateProject.php
resources/js/Pages/Project/Partials/Details.vue
resources/js/Shared/AddAuthor.vue
resources/js/Shared/Submission.vue

Fixes #298 & #306

---

app/Http/Controllers/DownloadController.php
resources/js/Pages/Public/Project/Layout.vue
resources/js/Shared/Submission.vue

Fixed non functional download buttons - submission, public pages

---

resources/js/Mixins/Global.js
resources/js/Pages/Project/Partials/Details.vue
resources/js/Pages/Project/Show.vue
resources/js/Pages/Public/Project/Study.vue
resources/js/Pages/Study/Datasets.vue

Enabled public datasets share URL (dropdown - clipboard copy) - fixes #195

Expose dataset url

---

app/Http/Controllers/ProjectController.php
app/Http/Resources/ProjectResource.php
app/Models/HasProjects.php
app/Models/HasStudies.php
app/Models/Project.php
resources/js/Pages/Public/Project/Layout.vue
resources/js/Pages/Public/Project/License.vue
resources/js/Pages/Public/Project/Show.vue
resources/js/Pages/Study/Files.vue
resources/js/Shared/ProjectCard.vue

Project-card ~ download button ~ non-functional bug fix
Various other formatting changes

Toggle upvote fix. Fixes #367

---

app/Http/Controllers/API/Bioschema/DataCatalogController.php
composer.json
composer.lock
package-lock.json
routes/api.php

- Installed composer - spatie bioschema package
- Extended API routes, controllers

Implemented bioschema - data catalogue

---

app/Http/Controllers/DatasetController.php
app/Http/Controllers/ProjectController.php
app/Models/Dataset.php
app/Models/Project.php
resources/js/Pages/Public/Datasets.vue
resources/js/Pages/Public/Projects.vue
resources/js/Shared/DatasetCard.vue
resources/js/Shared/DatasetSearch.vue
resources/js/Shared/Pagination.vue
resources/js/Shared/ProjectSearch.vue

Fixes #132
- Pagination
- Search
- Sort by filters
- Grid / list modes
for projects / datasets
Extended model to enable filter by scope
Disabled cached for search results for testing

Sorting/Searching/Filtering of Projects and Studies - Fixes #132

---

app/Http/Controllers/API/Bioschema/BiochemaController.php
app/Http/Controllers/API/Bioschema/ProjectController.php
app/Models/Bioschema/BioSchema.php
app/Models/Bioschema/Project.php
app/Models/Bioschema/Study.php
routes/api.php

Define project as bioschema study
Implement the project schema

Route the project, Study, Dataset schemas

---

resources/js/Pages/Project/Show.vue
resources/js/Shared/AddCitation.vue

Fix citation bug & make citation card clickable.

---

app/Http/Controllers/CitationController.php
app/Http/Middleware/HandleInertiaRequests.php
database/migrations/2022_08_29_115346_update_author_table.php
resources/js/Pages/Project/Show.vue
resources/js/Pages/Public/Project/Show.vue
resources/js/Shared/AddAuthor.vue
resources/js/Shared/AddCitation.vue

- Make author cards clickable.
- UI changes.

Update author import API. Fixes #400

---

app/Actions/Project/UpdateProject.php
app/Http/Controllers/DatasetController.php
app/Http/Controllers/DownloadController.php
app/Http/Controllers/DraftController.php
app/Http/Controllers/FileSystemController.php
app/Jobs/ProcessDraft.php
app/Models/Dataset.php
app/Models/Project.php
app/Models/Study.php
app/Providers/CephStorageServiceProvider.php
config/app.php
config/filesystems.php
config/jetstream.php
resources/js/Shared/Submission.vue

Migration to Ceph storage
Submission process updates
Bug fixes

Ceph storage

---

app/Actions/Project/ArchiveProject.php
app/Http/Controllers/ProjectController.php
resources/js/Pages/Project/Partials/Archive.vue
resources/js/Pages/Project/Partials/Details.vue
resources/js/Pages/Project/Partials/Unarchive.vue
resources/js/Pages/Project/Settings.vue
resources/js/Pages/Project/Show.vue
resources/js/Pages/Study/Datasets.vue
resources/js/Pages/Study/Index.vue
resources/js/Pages/Study/Partials/Details.vue
resources/js/Shared/Submission.vue
routes/web.php

Fixes #44 
Fixes #43 
Fixes #235 
Fixes #389

Various bug fixes

---

resources/js/Pages/Welcome.vue
resources/views/vendor/cookie-consent/dialogContents.blade.php

Welcome page horizontal image overflow and cookie banner hidden element bugs resolved

fix: Welcome page & cookie banner bugs resolved

---

app/Http/Controllers/Admin/LicenseController.php
app/Http/Controllers/ProjectController.php
app/Policies/ProjectPolicy.php
resources/js/Pages/Public/Project/Studies.vue
resources/js/Pages/Public/Project/Study.vue
resources/js/Shared/SelectRich.vue
routes/web.php

Public poject studies are dynamically loaded now
Rich select is extended to show description
Public project view policy updated
Study page extended to show sample composition
Study page - datasets meta info display bug fixed
Web routes extended to accommodate studies end point Study share link bug fix

fix: various bug fixes and updates

---

app/Http/Controllers/DashboardController.php
app/Http/Controllers/StudyController.php
app/Models/Study.php
resources/js/Pages/Starred.vue
resources/js/Pages/Study/Layout.vue
resources/js/Shared/StudyCard.vue
routes/web.php

fix: Add star to studies.

---

resources/js/Pages/Project/Show.vue
resources/js/Pages/Public/Project/Show.vue
resources/js/Shared/AuthorCheckbox.vue

fix: Broken Orcid link.

---

app/Models/HasDOI.php

 fix: extend DataCite

---

app/Http/Controllers/DashboardController.php
resources/js/Pages/Project/Index.vue

fix: add more meta-data to project list.

---

app/Http/Controllers/DashboardController.php
resources/js/Pages/Project/Index.vue

fix: star shared project issue

---

app/Http/Controllers/CitationController.php
database/migrations/2022_11_25_081235_update_citation_text_abstract_citations_table.php
resources/js/Shared/AuthorCard.vue
resources/js/Shared/ManageAuthor.vue
resources/js/Shared/ManageCitation.vue

Fixex below issues
- citation_text 500 error.
- null check for authorAffiliation.
- remove mandate check for abstract.
- add placeholder text for citation_text.
- ordering authors back to [given name] [family name] 
- disappearing issue after edit and going back.

fix: citation and author issues.

---

app/Http/Middleware/HandleInertiaRequests.php
resources/js/Pages/Project/Partials/Delete.vue

fix: use env variable for project deletion cool off period

---

resources/js/Shared/ProjectCard.vue

fix: display keywords to public project view

---

app/Http/Controllers/Admin/LicenseController.php
app/Http/Controllers/ProjectController.php
database/seeders/LicenseSeeder.php
tests/Feature/ManageAuthorsTest.php
tests/Feature/ManageCitationsTest.php
tests/Feature/ManageLicenseTest.php

feat: test case for license

---

app/Http/Controllers/DatasetController.php
app/Http/Controllers/ProjectController.php
app/Models/Project.php
app/Models/Study.php
resources/js/Shared/Search.vue

auto hide search tab
fixes #509

fix: remove archived project from active index & view

---

resources/js/Pages/Study/Datasets.vue
resources/js/Pages/Study/Index.vue
resources/js/Shared/Submission.vue

fix: upload screen return route issues.

---

app/Actions/Jetstream/InviteTeamMember.php
app/Actions/Project/InviteProjectMember.php
app/Actions/Study/InviteStudyMember.php
app/Http/Controllers/Admin/UsersController.php
app/Http/Middleware/HandleInertiaRequests.php
app/Jobs/DeleteAuthors.php
app/Models/User.php
app/Notifications/ProjectInviteNotification.php
app/Notifications/StudyInviteNotification.php
app/Notifications/TeamInvitationNotification.php
database/migrations/2023_01_17_105727_create_notifications_table.php
resources/js/Layouts/AppLayout.vue
resources/js/Shared/Notification.vue
routes/web.php

Fixes #106 #748 
[screen-capture (6).webm](https://user-images.githubusercontent.com/54287612/213196078-464963d8-c0c3-4e92-85d5-9f9f462c1f68.webm)

feat: notification

---

app/Actions/Fortify/CreateNewUser.php
app/Actions/Fortify/UpdateUserProfileInformation.php
app/Http/Controllers/API/Auth/RegisterController.php
app/Http/Controllers/Admin/UsersController.php
app/Http/Middleware/HandleInertiaRequests.php
app/Models/User.php
database/migrations/2022_12_27_123125_add_orcid_id_column_users_table.php
resources/js/Pages/Auth/Register.vue
resources/js/Pages/Console/Users/Index.vue
resources/js/Pages/Console/Users/Partials/UserProfile.vue
resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue
resources/js/Shared/SelectOrcidId.vue

feat: ask for orcid during registration

---

app/Http/Controllers/ApplicationController.php
resources/js/Pages/Public/Project/Download.vue
resources/js/Pages/Public/Project/Files.vue
resources/js/Pages/Public/Project/Layout.vue

feat: multilocate download option

---

resources/js/Pages/Project/Show.vue
resources/js/Pages/Study/Layout.vue

feat: add edit button to project and study names

---

resources/js/Mixins/Global.js
resources/js/Shared/ManageAuthor.vue
resources/js/Shared/ManageCitation.vue

fix: extract doi from URL.

---

resources/js/Pages/Public/Project/Files.vue

fix: download button issue

---

app/Http/Controllers/ApplicationController.php

fix: public studies route issue

---

resources/js/Pages/Console/Users/Partials/UserProfile.vue
resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue

Enhancements of ORCID functions

---

app/Console/Commands/SanitizeDatasets.php
app/Http/Controllers/DatasetController.php
resources/js/App/Onboarding.vue
resources/js/Shared/SpectraEditor.vue
resources/js/Shared/SpectraViewer.vue

fixes  Adapt the code to NMRium data schema v4 #824 
This solves the problem in submission for proceeding from step 1 to 2
And fixes saving nmrium info to the datasets and their display

Nmrium info new version

---

resources/js/Pages/Study/About.vue
resources/js/Shared/Submission.vue

fix: add error message when SMILES not parsed
Fixes #734

Smiles error

---

resources/js/Pages/Announcement/Index.vue

fixes #856
[screen-capture (12).webm](https://github.com/NFDI4Chem/nmrxiv/assets/54287612/fd9eefc0-66c3-4d55-b149-881dcf75d1e7)

fix: announcement empty search

---

app/Http/Controllers/Admin/UsersController.php
app/Notifications/ProjectInviteNotification.php
app/Notifications/StudyInviteNotification.php
app/Notifications/TeamInvitationNotification.php
resources/js/Layouts/AppLayout.vue
resources/js/Shared/Notification.vue
routes/web.php

[screen-capture (9).webm](https://github.com/NFDI4Chem/nmrxiv/assets/54287612/5df20a7f-b01f-478d-a839-4d2dd5022659)

fix: update notification view

---

resources/js/Pages/Study/About.vue
resources/js/Shared/Submission.vue

fixes #858
[screen-capture (11).webm](https://github.com/NFDI4Chem/nmrxiv/assets/54287612/85d1a78b-97f9-49c2-9238-5687511f606a)

fix: clear error message

---

resources/js/Pages/Project/Show.vue
resources/js/Pages/Public/Project/Show.vue

fix: add the doi badge back

---

app/Console/Kernel.php
config/database.php

and take backup only in production

fix: exclude nmrium and versions tables

---

docs/community/workshops.md

docs: add NMR Task Force Meeting to the workshops

---

resources/js/Pages/Project/Show.vue
resources/js/Pages/Study/Index.vue
resources/js/Pages/Study/Layout.vue

fix: disable action when project is deleted.

---

docs/introduction/data/schemas.md

docs: revisit and review data schemas

---

app/Events/DraftProcessed.php
app/Jobs/ProcessSubmission.php
app/Listeners/ProjectArchival.php
app/Listeners/SendDraftProcessedNotification.php
app/Mail/ProjectPublishNotifyAdmins.php
app/Models/Project.php
app/Notifications/ProjectPublishNotificationToAdmins.php
resources/views/vendor/mail/project-publish-notify-admins.blade.php

and publish notification via event fixes #515

fix: notify admin on project release

---

database/seeders/LicenseSeeder.php

fix: update license's abbreviations

---

app/Actions/Fortify/UpdateUserProfileInformation.php
resources/js/Pages/Auth/Login.vue
resources/js/Pages/Auth/Register.vue
resources/js/Pages/Console/Users/Partials/UserProfile.vue

fix: update user error fix

---

app/Models/Project.php

fix: authors sorting issue

---

resources/js/Shared/CitationCard.vue

fix: citation link

---

resources/js/Shared/ManageCitation.vue

fix: enable addition of duplicate citations

---

resources/js/Pages/Public/Project/Show.vue

fix: hide organism if null

---

resources/js/Shared/ManageAuthor.vue

fix: enable addition of multiple authors at once.

---

resources/js/Pages/Welcome.vue

fix: add missing dot.

---

app/Models/HasDOI.php
app/Services/DOI/DataCite.php

provide ORCID and other metadata and refactor
Fixes: #952, #990

Datacite properties

---

resources/js/Shared/Citation.vue

Citation styles

---

resources/js/App/StructureSearch.vue
resources/js/Layouts/AppLayout.vue
resources/js/Pages/Upload.vue

Multiple fixes

---

app/Http/Controllers/DashboardController.php
app/Http/Controllers/DraftController.php
app/Http/Controllers/UploadController.php
app/Models/Draft.php
resources/js/Pages/Project/Index.vue
resources/js/Pages/Upload.vue

fixes #1092
[screen-capture (30).webm](https://github.com/NFDI4Chem/nmrxiv/assets/54287612/91e18551-4811-4573-a300-45f4d0dddcc7)

fix: clicking draft should open last step

---

app/Http/Resources/ProjectResource.php
resources/js/Pages/Project/Index.vue
resources/js/Pages/Project/Show.vue
resources/js/Pages/Public/Project/Show.vue
resources/js/Shared/ShowProjectDates.vue

fix: add date of publication

---

.github/workflows/release-please.yml

- resolves node v16 deprecation warning.

fix: upgraded the release please action version from v3 to v4.

---

app/Actions/Project/UpdateDOI.php
app/Http/Controllers/API/Schemas/DataCite/DOIController.php
app/Jobs/ProcessProject.php
app/Jobs/ProcessSubmission.php
app/Models/HasDOI.php
app/Services/DOI/DOIService.php
app/Services/DOI/DataCite.php
routes/api.php

fixes https://github.com/NFDI4Chem/nmrxiv/issues/512

feat: add DataCite relatedIdentifier to link projects, studies, datasets.

---

resources/js/Pages/About.vue
resources/js/Pages/Study/Datasets.vue
resources/js/Shared/SpectraViewer.vue

Added missing datasets info in private study views

fix: formatting changes, spectra view defined height

---

app/Jobs/ProcessSubmission.php
app/Models/HasDOI.php

fix: add related identifiers to the doi metadata of separate samples.

---

resources/js/Pages/Welcome.vue

fix: add links to the homepage metrics

---

app/Console/Commands/UpdateDOI.php
app/Console/Commands/UpdateProjectsDOI.php

fix: update DataCite Meta data for unpublished projects

---

resources/js/App/Tour.vue
resources/js/Pages/Public/Project/Samples.vue
resources/js/Pages/Study/Index.vue
resources/js/Pages/Study/Layout.vue
resources/js/Pages/Study/Partials/Create.vue
resources/js/Pages/Study/Partials/Delete.vue
resources/js/Shared/Citation.vue
resources/js/Shared/Submission.vue

fix: replace the word "study" with "sample"

---

app/Http/Controllers/API/Schemas/Bioschemas/BioschemasController.php

fix: unify studies and datasets naming in bioschemas and datacite

---

app/Http/Controllers/API/Schemas/Bioschemas/BioschemasController.php
app/Http/Controllers/API/Schemas/DataCite/DataCiteController.php
routes/api.php

fix: comment out methods to generate schema by name

---

resources/js/Shared/ManageAuthor.vue

fix: author button styling issue

---

.env.example
app/Console/Commands/SanitizeMolecules.php
config/services.php

fix:move hardcoded urls to env and config files

---

resources/js/Pages/Upload.vue
resources/js/Shared/DraftSearch.vue

This pull request adds a search and pagination feature to the draft list in the `Upload.vue` page, improving usability for users managing large numbers of drafts. The changes include a new `DraftSearch` component for filtering drafts by name, description, ID, or key, and pagination controls for navigating through filtered results.
These changes make it easier for users to find and manage drafts, especially when dealing with a large number of items.

feat: enable pagination and search based filtering for drafts.
